
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MTHAN = 16;
  public static final int STRING_LITERAL = 42;
  public static final int LBRACKET = 11;
  public static final int EQUALITY = 26;
  public static final int CHAR_LITERAL = 43;
  public static final int ASTERISK = 6;
  public static final int FSLASH = 7;
  public static final int RAT_LITERAL = 46;
  public static final int MINUS = 4;
  public static final int LSQUAREBRACKET = 9;
  public static final int IMPLICATION = 19;
  public static final int SEMICOLON = 21;
  public static final int LTHAN = 15;
  public static final int IN = 41;
  public static final int TDEF = 28;
  public static final int COMMA = 25;
  public static final int FI = 36;
  public static final int PIPEPIPE = 17;
  public static final int PLUS = 5;
  public static final int IF = 34;
  public static final int EXCLAMATION = 2;
  public static final int DOT = 24;
  public static final int EOF = 0;
  public static final int OD = 40;
  public static final int RETURN = 31;
  public static final int RBRACKET = 12;
  public static final int error = 1;
  public static final int EXCLAMATIONEQUALITY = 20;
  public static final int FDEF = 29;
  public static final int COLONCOLON = 13;
  public static final int EQUALITYEQUALITY = 27;
  public static final int FOREACH = 37;
  public static final int RSQUAREBRACKET = 10;
  public static final int COLON = 14;
  public static final int ELSE = 35;
  public static final int LBRACE = 22;
  public static final int READ = 32;
  public static final int CARAT = 8;
  public static final int WHILE = 30;
  public static final int LTHANEQUALITY = 18;
  public static final int RBRACE = 23;
  public static final int AMPERSANDAMPERSAND = 3;
  public static final int FLOAT_LITERAL = 45;
  public static final int DO = 39;
  public static final int PRINT = 33;
  public static final int INTEGER_LITERAL = 44;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCLAMATION",
  "AMPERSANDAMPERSAND",
  "MINUS",
  "PLUS",
  "ASTERISK",
  "FSLASH",
  "CARAT",
  "LSQUAREBRACKET",
  "RSQUAREBRACKET",
  "LBRACKET",
  "RBRACKET",
  "COLONCOLON",
  "COLON",
  "LTHAN",
  "MTHAN",
  "PIPEPIPE",
  "LTHANEQUALITY",
  "IMPLICATION",
  "EXCLAMATIONEQUALITY",
  "SEMICOLON",
  "LBRACE",
  "RBRACE",
  "DOT",
  "COMMA",
  "EQUALITY",
  "EQUALITYEQUALITY",
  "TDEF",
  "FDEF",
  "WHILE",
  "RETURN",
  "READ",
  "PRINT",
  "IF",
  "ELSE",
  "FI",
  "FOREACH",
  "IDENTIFIER",
  "DO",
  "OD",
  "IN",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "RAT_LITERAL"
  };
}

